### ISSUE TITLE
Fresh build produces changes in four reference image files

### ISSUE THREAD

**Issue by mohawkjohn** [Arafatk/magick-rubyplot#15]
It seems like this shouldn't happen.

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   spec/reference_images/bar_title.png
	modified:   spec/reference_images/dot.png
	modified:   spec/reference_images/line.png
	modified:   spec/reference_images/scatter.png
```

I haven't actually done anything but run the specs. Why does just running the specs create changes?

**Comment by Arafatk** [comment]
I am really sorry for this issue.  
This was a totally avoidable mistake.     
I have solved it in this [commit](https://github.com/Arafatk/magick-rubyplot/commit/2f56c5ae521da5a2b4a2d786118b43e7eb13b99b)
