### ISSUE TITLE
Background gradient should be off by default

### ISSUE THREAD

**Issue by mohawkjohn** [Arafatk/magick-rubyplot#17]

**Comment by Arafatk** [comment]
There is a [classic white](https://github.com/Arafatk/magick-rubyplot/blob/master/lib/rubyplot/artist/theme_constants.rb#L31) theme with no gradient.    
I will change that to the default theme.

**Comment by Arafatk** [comment]
Solved by [commit](https://github.com/Arafatk/magick-rubyplot/commit/fab6d0e022d3548e30c0ddc541b3d7eec66efed5)

**Comment by translunar** [comment]
If you mention something like "fixes #17" in the commit description, it'll close the issue for you automatically, by the way.

**Comment by arafatkatze** [comment]
That's really nice.           
Thanks for the idea...
