### ISSUE TITLE
Magick Plot and Gr Plot Integration

### ISSUE THREAD

**Issue by arafatkatze** [Arafatk/magick-rubyplot#22]
1. Merge both the repos with complete history in a new repository     
2. Solve Travis issues for [GR Plot](https://github.com/pgtgrly/GRruby-extension).  
3. Make a common test suite for both the repositories 
4. Solve geometry issues and pre-existing bugs in magickplot
4. Complete the figure class -> All plots from both the repositories 
5. Remove original documentation for Magick Plot and make a single unified documentation that explains the new usage function.    
6. Restructure the repo and make it easy to use and understand both for developers and users.

**Comment by v0dro** [comment]
I'm making this into a checklist. Please tick off the features you have already implemented.

**Comment by v0dro** [comment]
- [x] Merge both the repos in a new repository.
- [ ] Add rake tasks for compiling and get GR specs running.
- [x] Make a common test suite for both the repositories
- [x] Make provisions for conditions require if GR or Magick is not present.
- [ ] Solve Travis issues for GR Plot.
- [ ] Solve geometry issues and pre-existing bugs in magickplot
- [ ] Complete the figure class -> All plots from both the repositories
- [ ] Remove original documentation for Magick Plot and make a single unified documentation that explains the new usage function.
- [ ] Restructure the repo and make it easy to use and understand both for developers and users.
