### ISSUE TITLE
Travis tests failing for the images.

### ISSUE THREAD

**Issue by Arafatk** [Arafatk/magick-rubyplot#5]
Currently, Travis tests seem to be failing because of architecture differences.  
Need to pass these tests be able to get decent correlation with the tolerance values locally and with travis.

**Comment by Arafatk** [comment]
Current build is passing and a new image comparison function has been introduced.

**Comment by mohawkjohn** [comment]
When you update issues and close them, it's really helpful to point to a
specific commit that solves them. This is standard practice; I'm not just
giving you busy-work.

**Comment by Arafatk** [comment]
@mohawkjohn Sorry, I almost forgot. 
This should have been taken care of.

**Comment by Arafatk** [comment]
[This commit](https://github.com/Arafatk/magick-rubyplot/commit/6d6c7c288b5345f3772ae81d4273decbcc4a025e) solves the issue.
