### ISSUE TITLE
Pie Charts construction

### ISSUE THREAD

**Issue by Arafatk** [Arafatk/magick-rubyplot#6]
Currently, Pie chart construction is an issue because Circles don't support the option of making Slices by making only a certain angle of a circle in the diagram.  This is a major roadblock to make Pie charts. 

An alternative option is to make a circle_slice draw function that supports making a circle's slice with the combination of ellipse(as a circle) and polygon to fill the space. This design should be tried out later when the project is more evolved.

**Comment by arafatkatze** [comment]
Pie charts are not a top priority plot and aren't very relevant for this software.   
https://www.quora.com/How-and-why-are-pie-charts-considered-evil-by-data-visualization-experts
